import { getSourceName, parseWebtoonUrl } from "./url";

export function makeSafeFilename(name?: string, fallback = "unnamed"): string {
  if (!name || !name.trim()) return fallback;
  const cleaned = name
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/[-\s]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return cleaned || fallback;
}

export interface ChapterNamingOptions {
  seriesTitle?: string;
  chapterNumber?: string;
  chapterTitle?: string;
  targetUrl?: string;
  sourceSite?: string;
}

export function resolveDownloadNaming(options?: ChapterNamingOptions): {
  seriesName: string;
  chapterNum: string;
  sourceSite: string;
  formattedPrefix: string;
} {
  let seriesName = options?.seriesTitle?.trim() || "";
  let chapterNum = options?.chapterNumber?.trim() || "";
  let targetUrl = options?.targetUrl?.trim() || "";
  let sourceSite = options?.sourceSite?.trim() || "";

  if (targetUrl) {
    if (!sourceSite) {
      sourceSite = getSourceName(targetUrl);
    }
    if (!seriesName || !chapterNum) {
      try {
        const parsed = parseWebtoonUrl(targetUrl);
        if (!seriesName && parsed.title) {
          seriesName = parsed.title.trim();
        }
        if (!chapterNum && parsed.chapterNumber) {
          chapterNum = parsed.chapterNumber.trim();
        }
      } catch (e) {}
    }
  }

  const safeSeries = makeSafeFilename(seriesName, "Webtoon");
  const safeChapter = makeSafeFilename(chapterNum, "1");
  const safeSource = makeSafeFilename(sourceSite, "WebtoonSource");

  const formattedPrefix = `${safeSeries}_Ch_${safeChapter}_${safeSource}`;

  return {
    seriesName: safeSeries,
    chapterNum: safeChapter,
    sourceSite: safeSource,
    formattedPrefix,
  };
}

export interface DetailedMetadataInfo {
  seriesTitle?: string;
  chapterNumber?: string;
  chapterTitle?: string;
  targetUrl?: string;
  sourceSite?: string;
  totalPanels?: number;
  extractedAt?: string;
  panelUrls?: string[];
  projectInfo?: {
    projectId?: string;
    jobId?: string;
    aspectRatio?: string;
    totalDurationSec?: number;
    aiModel?: string;
  };
}

export function generateMetadataText(info: DetailedMetadataInfo): string {
  const timestamp = info.extractedAt || new Date().toISOString();
  const dateStr = new Date(timestamp).toLocaleString("en-US", {
    dateStyle: "full",
    timeStyle: "medium",
  });

  const lines: string[] = [];
  lines.push("==========================================================================");
  lines.push("                  SONIKOMA WEBTOON STUDIO - METADATA REPORT               ");
  lines.push("==========================================================================");
  lines.push("");
  lines.push(`Series Title    : ${info.seriesTitle || "Unknown Series"}`);
  lines.push(`Chapter / Ep    : Chapter ${info.chapterNumber || "1"}${info.chapterTitle ? ` - ${info.chapterTitle}` : ""}`);
  lines.push(`Source Website  : ${info.sourceSite || "Webtoon Source"}`);
  lines.push(`Source URL      : ${info.targetUrl || "N/A"}`);
  lines.push(`Extraction Date : ${dateStr}`);
  lines.push(`Total Panels    : ${info.totalPanels ?? (info.panelUrls?.length || 0)}`);
  lines.push("");

  if (info.projectInfo) {
    lines.push("--------------------------------------------------------------------------");
    lines.push("                      PROJECT & COMPILER DETAILS                          ");
    lines.push("--------------------------------------------------------------------------");
    if (info.projectInfo.projectId) lines.push(`Project ID      : ${info.projectInfo.projectId}`);
    if (info.projectInfo.aspectRatio) lines.push(`Aspect Ratio    : ${info.projectInfo.aspectRatio}`);
    if (info.projectInfo.totalDurationSec) lines.push(`Total Duration  : ${info.projectInfo.totalDurationSec}s`);
    if (info.projectInfo.aiModel) lines.push(`AI Model        : ${info.projectInfo.aiModel}`);
    lines.push("");
  }

  if (info.panelUrls && info.panelUrls.length > 0) {
    lines.push("--------------------------------------------------------------------------");
    lines.push("                        PANEL IMAGE INVENTORY                             ");
    lines.push("--------------------------------------------------------------------------");
    info.panelUrls.forEach((url, idx) => {
      const numStr = String(idx + 1).padStart(3, "0");
      lines.push(`Panel #${numStr} : ${url}`);
    });
    lines.push("");
  }

  lines.push("==========================================================================");
  lines.push("Generated by Sonikoma Webtoon Studio | AI-Powered Webtoon to Video Engine");
  lines.push("==========================================================================");
  lines.push("");

  return lines.join("\n");
}

export function generateMetadataReadme(info: DetailedMetadataInfo): string {
  const timestamp = info.extractedAt || new Date().toISOString();
  const dateStr = new Date(timestamp).toLocaleString("en-US", {
    dateStyle: "full",
    timeStyle: "medium",
  });

  return `# ${info.seriesTitle || "Webtoon Series"} - Chapter ${info.chapterNumber || "1"}

> **Scraped & Packaged by Sonikoma AI Webtoon Studio**  
> *Export Date: ${dateStr}*

---

## 📌 Chapter Information
- **Series Title**: ${info.seriesTitle || "Unknown Series"}
- **Chapter / Episode**: Chapter ${info.chapterNumber || "1"} ${info.chapterTitle ? `(${info.chapterTitle})` : ""}
- **Source Website**: [${info.sourceSite || "Webtoon Source"}](${info.targetUrl || "#"})
- **Source URL**: \`${info.targetUrl || "N/A"}\`
- **Total Panels**: **${info.totalPanels ?? (info.panelUrls?.length || 0)}**

${
  info.projectInfo
    ? `---

## 🎬 Project & Compiler Metadata
- **Project ID**: \`${info.projectInfo.projectId || "N/A"}\`
- **Aspect Ratio**: ${info.projectInfo.aspectRatio || "9:16"}
- **Estimated Video Duration**: ${info.projectInfo.totalDurationSec || 0}s
- **AI Processing Model**: \`${info.projectInfo.aiModel || "Default Engine"}\`
`
    : ""
}

---

## 🖼️ Panel Image Inventory

| # | Panel Filename | Original Image Source URL |
|---|---|---|
${(info.panelUrls || [])
  .map(
    (url, idx) =>
      `| ${idx + 1} | \`${info.seriesTitle ? makeSafeFilename(info.seriesTitle) : "Webtoon"}_Ch_${info.chapterNumber || "1"}_img_${String(idx + 1).padStart(3, "0")}\` | [Link](${url}) |`
  )
  .join("\n")}

---

*Generated automatically by [Sonikoma AI Webtoon Studio](https://sonikoma.ai)*
`;
}
