import { ImageTool } from "@/features/editor_image/hooks/useImageEditorState";

export interface ImageEditorSidebarProps {
  activeTab: ImageTool;
  setActiveTab: (tab: ImageTool) => void;
  handleSaveTrainingData: () => Promise<void>;
  slices: any[];
  setSlices: any;
  editingImageIdx: number;
  scrapedImages: string[];
  isMerging: boolean;
  handleMergeWithNext: any;
  editCropTop: number;
  editCropBottom: number;
  editCropLeft: number;
  editCropRight: number;
  setEditCropTop: (v: number) => void;
  setEditCropBottom: (v: number) => void;
  setEditCropLeft: (v: number) => void;
  setEditCropRight: (v: number) => void;
  zoom: number;
  setZoom: (v: number) => void;
  isTransforming: boolean;
  handleTransform: (action: string, param: string) => void;
  handleResetCropBounds: () => void;
  activeStoryboardPanel: any;
  handleModifyBrightness: any;
  handleModifyContrast: any;
  handleModifySaturation: any;
  handleModifyFilterPreset: any;
  handleModifyGrayscale: any;
  handleModifyDuration: any;
  handleModifyMotionType: any;
  handleModifySpeechText: any;
  handleModifyNarrative?: any;
  handleModifyVisualDescription?: any;
  handleModifySfx: any;
  handleModifyCropPadding: any;
  setScrapedImages: any;
  setPanels: any;
  addNotification: any;
  fetchWithInterceptor: any;
  setConsoleLogs: any;
  editMode: any;
  setEditMode: any;
  brushSize: number;
  setBrushSize: any;
  brushAction: any;
  setBrushAction: any;
  handleClearBrushMask: any;
  detectionStyle: any;
  setDetectionStyle: any;
  eraseMethod: any;
  setEraseMethod: any;
  sensitivity: number;
  setSensitivity: any;
  dilation: number;
  setDilation: any;
  inpaintRadius: number;
  setInpaintRadius: any;
  debugMode: boolean;
  setDebugMode: any;
  fillColor: string;
  setFillColor: any;
  textBgColor?: string;
  setTextBgColor?: any;
  ocrLang: string;
  setOcrLang: any;
  gpu: boolean;
  setGpu: any;
  morphKernelSize: number;
  setMorphKernelSize: any;
  morphShape: string;
  setMorphShape: any;
  useCustomColorTarget: boolean;
  setUseCustomColorTarget: any;
  customColorTarget: string;
  setCustomColorTarget: any;
  customColorTolerance: number;
  setCustomColorTolerance: any;
  splitPosition: number;
  setSplitPosition: any;
  splitLines: number[];
  setSplitLines: any;
  showSplitPosition: boolean;
  setShowSplitPosition: any;
  setSelectedSliceId: any;
  handleAddSplitLine: any;
  handleRemoveSplitLine: any;
  handleExecuteHorizontalSplit: any;
  isSavingEdit: boolean;
  imageUrl: string | null;
  magneticSnap: boolean;
  setMagneticSnap: any;
  detectedGutters: number[];
  setDetectedGutters: any;
  selectedSliceId: string | null;
  editAutoTrim: boolean;
  handlePushToSlices: any;
  autoPushOnDraw: boolean;
  setAutoPushOnDraw: any;
  handleClearAllSlices: any;
  handleNudge: any;
  handleSelectSlice: any;
  handleDeleteSlice: any;
  handleCropSingleSlice: any;
  isCroppingSlice: string | null;
  handleDetectPanels: any;
  handleCancelDetect: () => void;
  isDetecting: boolean;
  handleCommitDetectedBoxes: any;
  detectedBoxes: any[];
  handleClearDetectedBoxes: any;
  handleExecuteSave: any;
}
